#!/bin/bash

# Update package index
sudo apt update

# Install nginx
sudo apt install nginx -y

# Configure custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/custom_404' << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        return 404 "Ceci n'est pas une page";
    }

    # Other configurations if any
}
EOF

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Remove default symlink to default site configuration
sudo rm /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
