#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# but for multiples of 3 print Fizz instead of the number
# and for the multiples of 5 print Buzz
# For numbers which are multiples of 3 and 5 print FizzBuzz
for number in {1..100}
do
    if [ $((number % 3)) -eq 0 ] && [ $((number % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((number % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((number % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$number"
    fi
done
