#!/usr/bin/env bash
# This script is displaying "bad luck" for the 4th iteration
# and "good luck" for the 8th iteration
# and "Best School" for the other iterations
for ((i=1; i<=10; i++))
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
