#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# But it displays "4" and then "bad luck from China"
# for the 4th iteration
# and "9" and then "bad luck from Japan"
# for the 9th iteration
# and "17" and then "bad luck from Italy"
# for the 17th iteration
i=1
while [ $i -le 20 ]
do
    if [ $i -eq 4 ]
    then
        echo "4"
        echo "bad luck from China"
    elif [ $i -eq 9 ]
    then
        echo "9"
        echo "bad luck from Japan"
    elif [ $i -eq 17 ]
    then
        echo "17"
        echo "bad luck from Italy"
    else
        echo $i
    fi
    i=$((i+1))
done
