#!/usr/bin/env bash
# script to check if a user exists on the system

if [ "$#" -eq 0 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

if sudo -u "$1" true 2>/dev/null; then
  sudo -u "$1" whoami
else
  echo "user $1 not found."
fi
